//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programacao2_final.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mercenarios
    {
        public int Idmerc { get; set; }
        public string rank { get; set; }
        public string nome { get; set; }
        public Nullable<double> pdia { get; set; }
        public string fotopath { get; set; }
    
        public virtual nomes nomes { get; set; }
    }
}
